-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 01:42:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT NOT NULL,
  `username` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(64) NOT NULL,
  `idAtivo` VARCHAR(1) NOT NULL DEFAULT 'S',
  `dtultacesso` DATETIME NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `idUsuario` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  INDEX `fk_administrador_usuario1_idx` (`idUsuario` ASC) ,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_administrador_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doador`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`doador` (
  `idUsuario` INT NOT NULL,
  `nmrazsocial` VARCHAR(45) NOT NULL,
  `nmfantasia` VARCHAR(45) NULL,
  INDEX `fk_doador_usuario_idx` (`idUsuario` ASC) ,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_doador_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rota`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`rota` (
  `idRota` INT NOT NULL AUTO_INCREMENT,
  `nmRota` VARCHAR(80) NOT NULL,
  `descRota` VARCHAR(45) NULL,
  PRIMARY KEY (`idRota`),
  UNIQUE INDEX `idRota_UNIQUE` (`idRota` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupoRua`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`grupoRua` (
  `idGrupo` INT NOT NULL,
  `qtdPopulacao` INT NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoDeficiencia`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`tipoDeficiencia` (
  `idEspecificacaoDeficiencia` INT NOT NULL,
  `nmDeficiencia` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idEspecificacaoDeficiencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idCategoria` INT NOT NULL,
  `nmCategoria` VARCHAR(40) NOT NULL,
  `categoriacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doacao`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`doacao` (
  `idDoacao` VARCHAR(45) NOT NULL,
  `idRotas` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `dtDoacao` DATETIME NULL,
  PRIMARY KEY (`idDoacao`),
  INDEX `fk_Agendamento_rotas_idx` (`idRotas` ASC) ,
  INDEX `fk_doacao_tipoDoacao_idx` (`idCategoria` ASC) ,
  INDEX `fk_doacao_doador_idx` (`idUsuario` ASC) ,
  CONSTRAINT `fk_Agendamento_rotas`
    FOREIGN KEY (`idRotas`)
    REFERENCES `mydb`.`rota` (`idRota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doacao_tipoDoacao`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `mydb`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doacao_doador`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`doador` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deficienciaGrupo`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`deficienciaGrupo` (
  `idGrupo` INT NOT NULL,
  `idTipoDeficiencia` INT NOT NULL,
  PRIMARY KEY (`idGrupo`, `idTipoDeficiencia`),
  INDEX `fk_deficienciaGrupo_idx` (`idTipoDeficiencia` ASC) ,
  INDEX `fk_grupoRua_idx` (`idGrupo` ASC) ,
  CONSTRAINT `fk_grupoRua`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `mydb`.`grupoRua` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipoDeficiencia`
    FOREIGN KEY (`idTipoDeficiencia`)
    REFERENCES `mydb`.`tipoDeficiencia` (`idEspecificacaoDeficiencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ponto`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`ponto` (
  `idPonto` INT NOT NULL,
  `idRota` INT NOT NULL,
  PRIMARY KEY (`idPonto`),
  INDEX `fk_ponto_rota_idx` (`idRota` ASC) ,
  CONSTRAINT `fk_ponto_rota`
    FOREIGN KEY (`idRota`)
    REFERENCES `mydb`.`rota` (`idRota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coordenadas`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`coordenadas` (
  `idCoordenada` INT NOT NULL,
  `XAxis` DOUBLE NULL,
  `YAxis` DOUBLE NULL,
  PRIMARY KEY (`idCoordenada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coordenadaPonto`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`coordenadaPonto` (
  `idCoordenada` INT NOT NULL,
  `idPonto` INT NOT NULL,
  PRIMARY KEY (`idCoordenada`, `idPonto`),
  INDEX `fk_coordenadas_idx` (`idCoordenada` ASC) ,
  INDEX `fk_ponto_idx` (`idPonto` ASC) ,
  CONSTRAINT `fk_ponto_has_coordenadas_coordenadas1`
    FOREIGN KEY (`idCoordenada`)
    REFERENCES `mydb`.`coordenadas` (`idCoordenada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coordenadaPonto_ponto1`
    FOREIGN KEY (`idPonto`)
    REFERENCES `mydb`.`ponto` (`idPonto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localGrupoRua`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`localGrupoRua` (
  `idPonto` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  PRIMARY KEY (`idPonto`, `idGrupo`),
  INDEX `fk_grupoRua_idx` (`idGrupo` ASC) ,
  CONSTRAINT `fk_ponto`
    FOREIGN KEY (`idPonto`)
    REFERENCES `mydb`.`ponto` (`idPonto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupoRua`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `mydb`.`grupoRua` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
