  -- MySQL Script generated by MySQL Workbench
  -- Wed May  1 18:12:32 2019
  -- Model: New Model    Version: 1.0
  -- MySQL Workbench Forward Engineering

  SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
  SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
  SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

  -- -----------------------------------------------------
  -- Schema tis_exemplo_2
  -- -----------------------------------------------------
  CREATE SCHEMA IF NOT EXISTS `tis_exemplo_2` DEFAULT CHARACTER SET utf8 ;
  USE `tis_exemplo_2` ;


  -- -----------------------------------------------------
  -- Table `tis_exemplo_2`.`ROTAMAPS`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `tis_exemplo_2`.`ROTAMAPS` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NMROTA` VARCHAR(80) NOT NULL,
    `QTDPESSOAS` VARCHAR(45) NULL,
    `DTINCLUSAO` DATETIME NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `ID_ROTA` (`ID` ASC) )
  ENGINE = InnoDB;

  -- -----------------------------------------------------
  -- Table `tis_exemplo_2`.`PONTOMAPS`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `tis_exemplo_2`.`PONTOMAPS` (
    `ID` INT NOT NULL,
    `IDROTA` INT NOT NULL,
    `LAT` VARCHAR(30) NOT NULL,
    `LNG` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `fk_ponto_rota_idx` (`IDROTA` ASC) ,
    CONSTRAINT `fk_ponto_rota`
      FOREIGN KEY (`IDROTA`)
      REFERENCES `ROTAMAPS` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION )
  ENGINE = InnoDB;

  -- -----------------------------------------------------
  -- Table `tis_exemplo_2`.`PONTOUSUARIO`
  -- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS `tis_exemplo_2`.`PONTOUSUARIO` (
    `ID` INT NOT NULL,
    `IDROTA` INT NOT NULL,
    `LAT` VARCHAR(30) NOT NULL,
    `LNG` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `fk_pontousuario_rota1_idx` (`IDROTA` ASC) ,
    CONSTRAINT `fk_pontousuario_rota1`
      FOREIGN KEY (`IDROTA`)
      REFERENCES `ROTAMAPS` (`ID`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;

  --
  -- Estrutura da tabela `doacao`
  --
  CREATE TABLE IF NOT EXISTS `tis_exemplo_2`. `doacao` (
    `ID` int(11) NOT NULL,
    `IDROTA` int(11) DEFAULT NULL,
    `NOME` varchar(50) NOT NULL,
    `DTDOACAO` date NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

  --
  -- Extraindo dados da tabela `doacao`
  --

  INSERT INTO `tis_exemplo_2`.`doacao` (`ID`, `IDROTA`, `NOME`, `DTDOACAO`) VALUES
  (4, 2, 'asd', '2019-03-22'),
  (6, 3, 'asd 2', '2019-03-22'),
  (7, 1, 'wer', '2019-03-22'),
  (8, 1, 'asdf', '2019-03-23'),
  (9, 3, '23456', '2019-03-30'),
  (10, 2, '34567890', '2019-03-23'),
  (11, 3, 'sdfghjk', '2019-03-23');

  -- --------------------------------------------------------

  --
  -- Estrutura da tabela `rota`
  --

  CREATE TABLE IF NOT EXISTS `tis_exemplo_2`. `rota` (
    `IDROTA` int(11) NOT NULL,
    `NMROTA` varchar(100) NOT NULL,
    `SGROTA` varchar(30) NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

  --
  -- Extraindo dados da tabela `rota`
  --

  INSERT INTO `tis_exemplo_2`.`rota` (`IDROTA`, `NMROTA`, `SGROTA`) VALUES
  (1, 'Área Hospitalar', 'area_hospitalar'),
  (2, 'Praça Savassi', 'praca_savassi'),
  (3, 'Praça da Liberdade', 'praca_liberdade');

  ALTER TABLE `tis_exemplo_2`.`doacao`
    ADD PRIMARY KEY (`ID`),
    ADD KEY `FK_ROTA` (`IDROTA`);

  ALTER TABLE `tis_exemplo_2`.`rota`
    ADD PRIMARY KEY (`IDROTA`);

  ALTER TABLE `tis_exemplo_2`.`doacao`
    MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

  ALTER TABLE `tis_exemplo_2`.`doacao`
    ADD CONSTRAINT `FK_ROTA` FOREIGN KEY (`IDROTA`) REFERENCES `rota` (`IDROTA`) ON DELETE CASCADE;

  SET SQL_MODE=@OLD_SQL_MODE;
  SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
  SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
